apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: personal-website
  description: The place to be
  tags:
    - typescript
  links:
    - url: https://clement.champouillon.com
      title: Personal website
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: development/guest
